apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::717018590712:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::717018590712:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NG35SBZJBWR6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-30T17:18:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1360"
  uid: 9ac5c7c8-e539-4de9-b798-fe92401fe993
